AllCops:
  Exclude:
    - 'views/**/*'
    - 'spec/support/graphql_response_mock.rb'
  TargetRubyVersion: 2.6

#################### Style ################################
Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  Description: 'Checks for trailing comma in argument lists.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-params-comma'
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

#################### Metrics ################################
Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
 Max: 15

Metrics/PerceivedComplexity:
 Max: 7
