version: '3.4'

services:
  app:
    build:
      context: .
      target: development
    command: bundle exec puma -p 4000
    env_file:
      - .env
      - .env.local
    ports:
      - "4000:4000"
    stdin_open: true
    volumes:
      - .:/app
    environment:
      TERM: xterm
